###
GET https://neuvax.github.io/MiniReto/api HTTP/1.1

###
POST https://neuvax.github.io/MiniReto/api HTTP/1.1
Content-Type: application/json

{
    "title": "Call of Duty: Black Ops 2",
    "company": "Activision",
    "year": 2016
}

###
DELETE https://neuvax.github.io/MiniReto/api/1 HTTP/1.1

###
PUT https://neuvax.github.io/MiniReto/api/1 HTTP/1.1
Content-Type: application/json

{
    "title": "Minecraft",
    "company": "Microsoft",
    "year": 2012
}